---
title: "p8105_hw6_bf2506"
author: "bf2506"
date: "2022-11-30"
output: github_document
---

```{r load package, message=FALSE, warning=FALSE}
library(tidyverse)
```

### Problem 2

```{r read homi_data}
homi_data = 
  read.csv("./data/homicide-data.csv") %>%
  janitor::clean_names()
```

Create a city_state variable, and a binary result variable of disposition. Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t report victim race. Also omit Tulsa, AL – this is a data entry mistake. For this problem, limit your analysis those for whom victim_race is white or black. Be sure that victim_age is numeric.
```{r}
homi_data = 
  homi_data %>% 
  mutate(city_state = paste(city, state, sep = ", ", collapse = NULL)) %>% 
  mutate(result = ifelse(disposition == "Closed by arrest", 1, 0),
         victim_age = as.numeric(victim_age)) %>%
  relocate(uid, city_state, everything()) %>% 
  filter( !(city_state %in% c("Dallas,TX", "Phoenix,AZ", " Kansas City,MO", "Tulsa,AL")) &
    victim_race %in% c("Black", "White"))
```
