p8105_hw6_bf2506
================
bf2506
2022-11-30

``` r
library(tidyverse)
```

### Problem 2

``` r
homi_data = 
  read.csv("./data/homicide-data.csv") %>%
  janitor::clean_names()
```

Create a city_state variable, and a binary resolved variable of
disposition. Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO –
these don’t report victim race. Also omit Tulsa, AL – this is a data
entry mistake. For this problem, limit your analysis those for whom
victim_race is white or black. Be sure that victim_age is numeric.

``` r
homi_data = 
  homi_data %>% 
  mutate(city_state = paste(city, state, sep = ", ", collapse = NULL)) %>% 
  mutate(resolved = as.numeric(disposition == "Closed by arrest"),
         victim_age = as.numeric(victim_age)) %>%
  relocate(uid, city_state, everything()) %>% 
  filter( !(city_state %in% c("Dallas,TX", "Phoenix,AZ", " Kansas City,MO", "Tulsa,AL")) &
    victim_race %in% c("Black", "White"))
```

    ## Warning in mask$eval_all_mutate(quo): 强制改变过程中产生了NA

For the city of Baltimore, MD, use the glm function to fit a logistic
regression with resolved vs unresolved as the outcome and victim age,
sex and race as predictors. Save the output of glm as an R object.

``` r
baltimore_df =
  homi_data %>%
  filter(city_state == "Baltimore, MD")

fit_logistic_balt = 
  glm(resolved ~ victim_age + victim_sex + victim_race, family = binomial(), data = baltimore_df) 
```

Apply the broom::tidy to this object; and obtain the estimate and
confidence interval of the adjusted odds ratio for solving homicides
comparing male victims to female victims keeping all other variables
fixed.

``` r
fit_balt_table = fit_logistic_balt %>% broom::tidy() 

result_est_confint = 
  fit_balt_table %>% 
  filter(term == "victim_sexMale") %>%
  mutate(OR = exp(estimate),
         confint_lower = exp(estimate - 1.96*std.error),
         confint_upper = exp(exp(estimate + 1.96*std.error))) %>%
  select(term, OR, confint_lower, confint_upper)

result_est_confint
```

    ## # A tibble: 1 × 4
    ##   term              OR confint_lower confint_upper
    ##   <chr>          <dbl>         <dbl>         <dbl>
    ## 1 victim_sexMale 0.426         0.325          1.75

- The estimate value of the adjusted odds ratio is 0.426
- The corresponding confidence interval is (0.325, 1.75)
